version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./HAMK-Edu:/var/www/html/
    networks:
      - lan

  db: # mysql database server
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always #this restarts the service upon any configuration changes
    environment: # to use and access MySQL server,we neet to set up an authentication environment
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "6034:3306"   #6034 in the local machine and 3306 in the container
    volumes: # it persists updates made to the database
      - dbdata:/var/lib/mysql
    networks:
      - lan

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - "82:80"
    environment:
      PMA_HOST: db
      PMA_ARBITARY: 1
    networks:
      - lan

volumes:
  dbdata:
networks:
  lan: